name: veracode-sast-scan
on: [push, pull_request, workflow_dispatch]
jobs:
  build-project:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
    
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: scan-target
          path: release.zip

  veracode-sast-scan:
    needs: [build-project]
    runs-on: ubuntu-latest
    name: veracode-sast-scan
    permissions:
      id-token: write
      contents: read
    container:
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: scan-target
          path: /tmp
          
      - name: pipeline-scan
        run: |
          java -jar /opt/veracode/pipeline-scan.jar \
            -vid "${{ secrets.VERACODE_API_KEY_ID }}" \
            -vkey "${{ secrets.VERACODE_API_KEY_SECRET }}" \
            --fail_on_severity="Very High, High, Medium" \
            --file /tmp/release.zip
        continue-on-error: true
        
      - name: save filtered results file
        uses: actions/upload-artifact@v3
        with:
          name: filtered-results
          path: filtered_results.json

  import-issues:
    needs: [veracode-sast-scan]
    runs-on: ubuntu-latest
    name: import-issues-to-github
#    permissions:
#      issues: write
    steps:
      - name: get scan results
        uses: actions/download-artifact@v3
        with:
          name: filtered-results
      - name: import flaws as issues
        uses: relaxnow/veracode-flaws-to-issues@npm-update
        with:
          scan-results-json: 'filtered_results.json'
          debug: true
